window.ECHO_TOPICS = [
  {
    id: "daily",
    title: "일상 대화",
    emoji: "☕",
    desc: "카페, 친구, 하루 이야기",
    lines: [
      { en: "How was your day?", ko: "오늘 하루 어땠어?" },
      { en: "It was pretty good, actually.", ko: "사실 꽤 괜찮았어." },
      { en: "Want to grab a coffee later?", ko: "나중에 커피 한잔 할래?" },
      { en: "Sure, I'm free after six.", ko: "좋아, 여섯 시 이후엔 가능해." },
      { en: "That sounds perfect.", ko: "완벽하네." },
      { en: "I'll text you when I'm nearby.", ko: "근처에 도착하면 문자할게." },
      { en: "Don't forget your umbrella.", ko: "우산 잊지 마." },
      { en: "Thanks for reminding me.", ko: "알려줘서 고마워." },
    ],
  },
  {
    id: "cafe",
    title: "카페 주문",
    emoji: "🧋",
    desc: "주문하고 받는 말",
    lines: [
      { en: "Hi, can I get an iced latte?", ko: "안녕하세요, 아이스 라떼 하나요?" },
      { en: "Would you like that with oat milk?", ko: "오트밀크로 하실래요?" },
      { en: "Yes, please. And not too sweet.", ko: "네, 너무 달지 않게 해주세요." },
      { en: "For here or to go?", ko: "매장에서 드실 건가요, 가져가실 건가요?" },
      { en: "To go, please.", ko: "가져갈게요." },
      { en: "That'll be five fifty.", ko: "5달러 50센트입니다." },
      { en: "Here's my card.", ko: "카드로 할게요." },
      { en: "Your drink will be ready shortly.", ko: "음료는 곧 나옵니다." },
    ],
  },
  {
    id: "work",
    title: "회사 / 미팅",
    emoji: "💼",
    desc: "업무에서 자주 쓰는 말",
    lines: [
      { en: "Can we push the meeting to three?", ko: "미팅을 세 시로 미룰 수 있을까요?" },
      { en: "I'll send the file by noon.", ko: "정오까지 파일을 보낼게요." },
      { en: "Let me double-check that.", ko: "한번 더 확인해 볼게요." },
      { en: "That works for me.", ko: "저한테는 괜찮아요." },
      { en: "Could you clarify that point?", ko: "그 부분을 좀 더 설명해 주실 수 있나요?" },
      { en: "I'll follow up after the call.", ko: "통화 후에 다시 연락드릴게요." },
      { en: "Great work on this project.", ko: "이번 프로젝트 정말 잘하셨어요." },
      { en: "Let's wrap this up.", ko: "이쯤에서 마무리합시다." },
    ],
  },
  {
    id: "travel",
    title: "여행",
    emoji: "✈️",
    desc: "공항, 호텔, 길 묻기",
    lines: [
      { en: "Where is the nearest subway station?", ko: "가장 가까운 지하철역이 어디인가요?" },
      { en: "How long does it take to get there?", ko: "거기까지 얼마나 걸려요?" },
      { en: "I'd like to check in, please.", ko: "체크인하고 싶습니다." },
      { en: "Is breakfast included?", ko: "조식이 포함되어 있나요?" },
      { en: "Could you recommend a good restaurant nearby?", ko: "근처 맛집 하나 추천해 주시겠어요?" },
      { en: "I think we're lost.", ko: "길 잃은 것 같아요." },
      { en: "Do you have a room available tonight?", ko: "오늘 밤 빈방 있나요?" },
      { en: "This is exactly what I needed.", ko: "이게 딱 필요했던 거예요." },
    ],
  },
  {
    id: "feelings",
    title: "감정 표현",
    emoji: "💬",
    desc: "기분과 생각을 말로",
    lines: [
      { en: "I'm feeling a bit overwhelmed today.", ko: "오늘은 좀 벅차네요." },
      { en: "That made my day.", ko: "덕분에 하루가 즐거워졌어요." },
      { en: "I know exactly how you feel.", ko: "기분이 어떤지 정확히 알겠어요." },
      { en: "I'm proud of how far you've come.", ko: "여기까지 온 게 정말 자랑스러워요." },
      { en: "Let's take it one step at a time.", ko: "한 걸음씩 해봐요." },
      { en: "I didn't mean to upset you.", ko: "기분 상하게 하려는 건 아니었어요." },
      { en: "This means a lot to me.", ko: "이건 저한테 정말 의미가 커요." },
      { en: "I'm glad we talked.", ko: "이야기해서 다행이에요." },
    ],
  },
  {
    id: "smalltalk",
    title: "스몰톡",
    emoji: "🌤️",
    desc: "가볍게 시작하는 대화",
    lines: [
      { en: "Nice weather today, isn't it?", ko: "오늘 날씨 좋네요, 그렇죠?" },
      { en: "Have you been here before?", ko: "여기 와본 적 있어요?" },
      { en: "What do you usually do on weekends?", ko: "주말엔 보통 뭐 하세요?" },
      { en: "I've been meaning to ask you something.", ko: "물어볼 게 있었어요." },
      { en: "That's interesting. Tell me more.", ko: "흥미롭네요. 더 이야기해 주세요." },
      { en: "I totally agree with you.", ko: "완전 동감이에요." },
      { en: "We should do this again sometime.", ko: "언제 또 이렇게 만나요." },
      { en: "It was really nice talking to you.", ko: "이야기해서 정말 좋았어요." },
    ],
  },
];
